server:
  port: 8082
 
eureka:
  client:
    serviceUrl:
      # 向每个注册中心注册
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
spring:
  application:
    name: spring-test-service
 # zipkin:
 #   base-url: http://192.168.184.131:9411/  #zipkin 的服务器端
 # sleuth:
 #   sampler:
 #     probability: 1.0   #采样比例，介于0到1之间，1表示全部采集  
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS