spring:
  profiles:
    active: instance2
  application:
    name: eureka-service
    
eureka:
  client:    
    register-with-eureka: false    #由于该应用为注册中心,设置为false,表明不向注册中心注册自己    
  server:
    enable-self-preservation: false
    fetch-registry: false   #是否从eureka服务器获取注册信息，这里不需要
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS

---

spring:
  profiles: instance1

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

---
spring:
  profiles: instance2

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#让多个eureka两两互相注册即可 实现了 Eureka 的高可用。一个挂了，不影响另一个
#启动不同的eureka需改 spring.profiles.active 的值，还有要去掉 Single instance only 的勾选


