server:
  port: 8887

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/stevenHewl/springclound.git   
          search-paths: '{application}'   #配置仓库路径，这里的配置会根据传入的应用名动态查找
          #username:    #仓库是public的就不需要用户名和密码
          #password:
  application:
    name: spring-cloud-config
  rabbitmq:
    host: localhost
    port: 5672
    username: steven
    password: 123456
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#要配置下面的节点，curl -X POST http://localhost:8887/actuator/bus-refresh ，这个请求才能是配置更新
management:
  endpoints:
    web:
      exposure:
        include: '*'
      
      
      